services:
  candm_migrations_manager.helper.entity:
    class: ClickAndMortar\AkeneoMigrationsManagerBundle\Helper\EntityHelper
    arguments:
    - '@service_container'
  candm_migrations_manager.helper.job:
    class: ClickAndMortar\AkeneoMigrationsManagerBundle\Helper\JobHelper
    arguments:
      - '@akeneo_batch.job.job_instance_repository'
      - '@doctrine.orm.entity_manager'
      - '@kernel'